### ISSUE TITLE
Practica de realidad aumentada con objetos 3d en heroku

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-equipo_prestadores-de-servicios#2]
[Práctica 3_Objeto 3d en heroku.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-equipo_prestadores-de-servicios/files/8321682/Practica.3_Objeto.3d.en.heroku.pdf)

**Comment by dulce-blm** [comment]
Calificación: 20 puntos.

**Comment by josealfredo79** [comment]
bien hecho y revisado...
